[package]
name = "narrow"
version = "0.2.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2021"
rust-version = "1.56.1"
description = "An implementation of Apache Arrow"
readme = "README.md"
repository = "https://github.com/teratide/narrow"
documentation = "http://docs.rs/narrow/"
license = "Apache-2.0 OR MIT"
keywords = ["Arrow"]
categories = ["data-structures"]

[features]
default = []

[dependencies]
# narrow-derive = { version = "0.1.0", path = "narrow-derive" }
paste = "1"

[dev-dependencies]
criterion = "0.3"

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1

[[bench]]
name = "narrow"
harness = false

[workspace]
members = [
  # "narrow-derive"
]
